spring.config.active.on-profile=prod

logging.level.root=ERROR

file.relays.json=/home/wim/public/waterwise/relay_config.json
file.groups.json=/home/wim/application/spring/hydraserver/groups.json
file.log=/home/wim/application/spring/hydraserver/processlog.log
file.error=/home/wim/application/spring/hydraserver/errorlog.log
file.batchtimes=/home/wim/application/spring/hydraserver/batchtimes.csv
log.path=/home/wim/temp/log/

#zoneUrl=https://api.hydrawise.com/api/v1/setzone.php
zoneUrl=https://vps.wimroukema.nl/waterwise/setzone.php