#spring.config.import=application_prod.properties
spring.profiles.active=prod
spring.application.name=hydraserver
server.port=8050

file.relays.json=relay_config.json
file.groups.json=groups.json
file.log=processlog.log
file.error=/home/wim/temp/log/errorlog.log
file.notification=/media/wim/DATA2/phpproc/pushnotifications/notification{number}_W.txt
file.batchtimes=batchtimes.csv
notification_link=https://tennis.wimroukema.nl/water/uni

rootUser=wim
batchUser=batch
zoneUrl=http://localhost/waterwise/setzone.php
#apiKey=D6B8-784B-784B-9F49
apiKey=xxxxxxxxxxxx
spring.mail.host=mail.wimroukema.nl
spring.mail.port=587
spring.mail.username=wim@wimroukema.nl
spring.mail.password=Wimr0609b:
spring.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mailsender.to=wim.roukema@home.nl
mailsender.mail.debug=true


