spring.config.active.on-profile=prod

logging.level.root=ERROR

file.error=/home/wim/temp/log/hydraserver_error.log
file.notification=/home/wim/phpproc/pushnotifications/notification{number}_W.txt
notification_link=https://tennis.wimroukema.nl/water/uni

apiKey=D6B8-784B-784B-9F49

zoneUrl=https://api.hydrawise.com/api/v1/setzone.php
#zoneUrl=https://vps.wimroukema.nl/waterwise/setzone.php

mailsender.mail.debug=false