spring.config.import=application_prod.properties
spring.profiles.active=prod
spring.application.name=hydraserver
server.port=8050

file.relays.json=/home/wim/Public/waterwise/relay_config_test.json
file.groups.json=/media/wim/DATA2/projects/golang/wshttpwaterserver/groups_test.json
file.log=/home/wim/eclipse-workspace/hydraserver/processlog.log
file.error=/home/wim/eclipse-workspace/hydraserver/errorlog.log
file.batchtimes=/home/wim/eclipse-workspace/hydraserver/batchtimes.csv
log.path=/home/wim/temp/log/
zoneUrl=http://localhost/waterwise/setzone.php
apiKey=D6B8-784B-784B-9F49